version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/opt/app/api
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum
