# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build

    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        SOURCE: "./user-auth"
        REMOTE_HOST: "ec2-3-21-94-125.us-east-2.compute.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/home/ec2-user/go/src/user-auth/"

    - name: Execute SSH commmands on remote server
      uses: JimCronqvist/action-ssh@master
      env:
        NAME: "ec2-user"
      with:
        hosts: 'ec2-3-21-94-125.us-east-2.compute.amazonaws.com'
        privateKey: ${{ secrets.PRIVATE_KEY }}
        command: pmgo restart server0
