# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build

    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        SOURCE: "./user-auth"
        REMOTE_HOST: ${{ secrets.SSH_HOST}}
        REMOTE_USER: "ec2-user"
        TARGET: "/home/ec2-user/go/src/user-auth/"

    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          pmgo restart server0
        host: ${{ secrets.SSH_HOST}}
        user: "ec2-user"
        key: ${{ secrets.PRIVATE_KEY}}
